
#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//weapons
#define INVENTORY_GAUNTLET			4
#define INVENTORY_SHOTGUN			5
#define INVENTORY_MACHINEGUN		6
#define INVENTORY_GRENADELAUNCHER	7
#define INVENTORY_ROCKETLAUNCHER	8
#define INVENTORY_LIGHTNING			9
#define INVENTORY_RAILGUN			10
#define INVENTORY_PLASMAGUN			11
#define INVENTORY_BFG10K			13
#define INVENTORY_GRAPPLINGHOOK		14
#define INVENTORY_NAILGUN			15
#define INVENTORY_PROXLAUNCHER		16
#define INVENTORY_CHAINGUN			17
#define INVENTORY_REDEEMER			18
//ammo
#define INVENTORY_SHELLS			19
#define INVENTORY_BULLETS			20
#define INVENTORY_GRENADES			21
#define INVENTORY_CELLS				22
#define INVENTORY_LIGHTNINGAMMO		23
#define INVENTORY_ROCKETS			24
#define INVENTORY_SLUGS				25
#define INVENTORY_BFGAMMO			26
#define INVENTORY_NAILS				27
#define INVENTORY_MINES				28
#define INVENTORY_BELT				29
#define INVENTORY_NUKE				30
//powerups
#define INVENTORY_HEALTH			31
#define INVENTORY_TELEPORTER		32
#define INVENTORY_MEDKIT			33
#define INVENTORY_KAMIKAZE			34
#define INVENTORY_PORTAL			35
#define INVENTORY_INVULNERABILITY	36
#define INVENTORY_QUAD				37
#define INVENTORY_ENVIRONMENTSUIT	38
#define INVENTORY_HASTE				39
#define INVENTORY_INVISIBILITY		40
#define INVENTORY_REGEN				41
#define INVENTORY_FLIGHT			42
#define INVENTORY_SCOUT				43
#define INVENTORY_GUARD				44
#define INVENTORY_DOUBLER			45
#define INVENTORY_AMMOREGEN			46

#define INVENTORY_REDFLAG			47
#define INVENTORY_BLUEFLAG			48
#define INVENTORY_NEUTRALFLAG		49
#define INVENTORY_REDCUBE			50
#define INVENTORY_BLUECUBE			51
//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

// if running the mission pack
#ifdef MISSIONPACK

//#error "running mission pack"

#endif

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMORCOMBAT		2
#define MODELINDEX_ARMORBODY		3
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7

#define MODELINDEX_GAUNTLET			8
#define MODELINDEX_SHOTGUN			9
#define MODELINDEX_MACHINEGUN		10
#define MODELINDEX_GRENADELAUNCHER	11
#define MODELINDEX_ROCKETLAUNCHER	12
#define MODELINDEX_LIGHTNING		13
#define MODELINDEX_RAILGUN			14
#define MODELINDEX_PLASMAGUN		15
#define MODELINDEX_BFG10K			16
#define MODELINDEX_GRAPPLINGHOOK	17
#define MODELINDEX_REDEEMER			18

#define MODELINDEX_SHELLS			19
#define MODELINDEX_BULLETS			20
#define MODELINDEX_GRENADES			21
#define MODELINDEX_CELLS			22
#define MODELINDEX_LIGHTNINGAMMO	23
#define MODELINDEX_ROCKETS			24
#define MODELINDEX_SLUGS			25
#define MODELINDEX_BFGAMMO			26
#define MODELINDEX_NUKE				27

#define MODELINDEX_TELEPORTER		28
#define MODELINDEX_MEDKIT			29
#define MODELINDEX_QUAD				30
#define MODELINDEX_ENVIRONMENTSUIT	31
#define MODELINDEX_HASTE			32
#define MODELINDEX_INVISIBILITY		33
#define MODELINDEX_REGEN			34
#define MODELINDEX_FLIGHT			35

#define MODELINDEX_REDFLAG			36
#define MODELINDEX_BLUEFLAG			37

// mission pack only defines

#define MODELINDEX_KAMIKAZE			38
#define MODELINDEX_PORTAL			39
#define MODELINDEX_INVULNERABILITY	40

#define MODELINDEX_NAILS			41
#define MODELINDEX_MINES			42
#define MODELINDEX_BELT				43

#define MODELINDEX_SCOUT			44
#define MODELINDEX_GUARD			45
#define MODELINDEX_DOUBLER			46
#define MODELINDEX_AMMOREGEN		47

#define MODELINDEX_NEUTRALFLAG		48
#define MODELINDEX_REDCUBE			49
#define MODELINDEX_BLUECUBE			50

#define MODELINDEX_NAILGUN			51
#define MODELINDEX_PROXLAUNCHER		52
#define MODELINDEX_CHAINGUN			53


//
#define WEAPONINDEX_GAUNTLET			1
#define WEAPONINDEX_MACHINEGUN			2
#define WEAPONINDEX_SHOTGUN				3
#define WEAPONINDEX_GRENADE_LAUNCHER	4
#define WEAPONINDEX_ROCKET_LAUNCHER		5
#define WEAPONINDEX_LIGHTNING			6
#define WEAPONINDEX_RAILGUN				7
#define WEAPONINDEX_PLASMAGUN			8
#define WEAPONINDEX_NAILGUN				9
#define WEAPONINDEX_PROXLAUNCHER		10
#define WEAPONINDEX_CHAINGUN			11
#define WEAPONINDEX_BFG					12
#define WEAPONINDEX_REDEEMER			13
#define WEAPONINDEX_GRAPPLING_HOOK		14
